name: Python linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linters:
    name: Run Python linters
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8]
        os:
          - ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: requestor

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          export PYTHONPATH="${PYTHONPATH}:/erigon_server"
          pip install -r requirements.txt
          pip install -r test-requirements.txt
      - name: Run mypy
        run: mypy --install-types --non-interactive .
      - name: Run pylint
        run: pylint **/*.py
