name: Runtime aarch64 build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run aarch64 build
    env:
      RUSTFLAGS: "-C link-arg=-s"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: >
            --release
            --features static-openssl
            --target aarch64-unknown-linux-musl
            --manifest-path ./ya-runtime-erigon/Cargo.toml
      - name: Copy binaries
        run: |
          mkdir build
          cp target/aarch64-unknown-linux-musl/release/ya-runtime-erigon build
