name: Runtime aarch64 build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run aarch64 build
    env:
      RUSTFLAGS: "-C link-arg=-s"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: >
            --release
            --target aarch64-unknown-linux-musl
      - name: Copy binaries
        run: |
          mkdir build
          cp ya-runtime-basic-auth/runtime-descriptor-template.json build
          cp target/aarch64-unknown-linux-musl/release/ya-runtime-basic-auth build
      - name: 'Build artifacts upload'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/build

